### ISSUE TITLE
Transparent modal over dashboard creation

### ISSUE THREAD

**Issue by weber8thomas** [depictio/depictio#207]

**Comment by weber8thomas** [comment]
Current ideas:

```css
html body {
    position: static !important;
}
```

```python
app.clientside_callback(
    """
    function() {
        document.html.body.style.position = 'static';
        return window.dash_clientside.no_update;
    }
    """,
    Output('dummy-output', 'children'),
    Input('dummy-input', 'value')
)
```
